Explorar los datos

In [346]:
# Importar bibliotecas para explorar datos
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [347]:
# Importar Datos
data = pd.read_csv('../data/ensanut2022_muestras.csv', sep=';')

In [348]:
data.head()

,FOLIO_I,FOLIO_INT,t_hora,t_min,t_sumai,t_sumaf,hora_ini_1,fecha_ini_1,hora_fin_1,fecha_fin_1,...,valor_VIT_D,fecdeterm_VIT_D,ponde_v,cuenta_mic,ponde_m12a49,ponde_m0a11,estrato,region,est_sel,upm
0,2022_01001004,2022_01001004_01,13,35,813,815,13:33:14,10/11/2022,13:35:20,10/11/2022,...,,,,0,,,3,4,13,0100100011320
1,2022_01001008,2022_01001008_01,20,44,1244,1244,20:34:12,20/11/2022,20:34:55,20/11/2022,...,,,,0,,,3,4,13,0100100011320
2,2022_01001008,2022_01001008_03,20,43,1243,1243,20:41:51,20/11/2022,20:42:23,20/11/2022,...,,,,0,,,3,4,13,0100100011320
3,2022_01001009,2022_01001009_02,9,26,561,566,09:21:48,10/11/2022,09:26:03,10/11/2022,...,,,"16452,5523392573",0,,,3,4,13,0100100011320
4,2022_01001011,2022_01001011_01,20,49,1249,1249,20:45:31,20/11/2022,20:46:06,20/11/2022,...,,,,0,,,3,4,13,0100100011320

In [349]:
data.info(verbose=True)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13899 entries, 0 to 13898
Data columns (total 132 columns):
 #    Column                Dtype
---   ------                -----
 0    FOLIO_I               object
 1    FOLIO_INT             object
 2    t_hora                int64
 3    t_min                 int64
 4    t_sumai               int64
 5    t_sumaf               int64
 6    hora_ini_1            object
 7    fecha_ini_1           object
 8    hora_fin_1            object
 9    fecha_fin_1           object
 10   tiempo1               int64
 11   resultado_1           int64
 12   hora_ini_2            object
 13   fecha_ini_2           object
 14   hora_fin_2            object
 15   fecha_fin_2           object
 16   tiempo2               int64
 17   resultado_2           int64
 18   hora_ini_3            object
 19   fecha_ini_3           object
 20   hora_fin_3            object
 21   fecha_fin_3           object
 22   tiempo3               int64
 23   resultado_3           int64
 24   hora_ini_4            object
 25   fecha_ini_4           object
 26   hora_fin_4            object
 27   fecha_fin_4           object
 28   tiempo4               int64
 29   resultado_4           int64
 30   hora_ini              object
 31   fecha_ini             object
 32   localizado            int64
 33   entidad               int64
 34   desc_ent              object
 35   municipio             int64
 36   desc_mun              object
 37   h0302                 int64
 38   h0303                 int64
 39   fech_nac              object
 40   sc                    object
 41   sv                    object
 42   sh                    object
 43   sm                    object
 44   int_hemoglobina       object
 45   nota1                 int64
 46   nota11                object
 47   nota00                object
 48   sc01                  object
 49   sc02                  object
 50   sc03                  object
 51   sc04                  object
 52   nota01                object
 53   san01                 object
 54   san02                 object
 55   san03                 object
 56   san04                 object
 57   san05                 object
 58   san06                 object
 59   nota02                object
 60   hb01                  object
 61   hb02                  object
 62   hb03                  object
 63   hb04                  object
 64   hb05                  object
 65   hb06a                 object
 66   hb06b                 object
 67   hb07a                 object
 68   hb07b                 object
 69   hb08                  object
 70   hb09                  object
 71   hb10                  object
 72   hb11                  object
 73   nota03                object
 74   mc01                  object
 75   mc02                  object
 76   mc03                  object
 77   comentario            object
 78   tiempo                int64
 79   hora_fin              object
 80   fecha_fin             object
 81   completa              int64
 82   otroent               object
 83   MATRIZ_SUERO          int64
 84   valor_AC_URICO        object
 85   fecdeterm_AC_URICO    object
 86   valor_ALBU            object
 87   fecdeterm_ALBU        object
 88   valor_COL_HDL         object
 89   fecdeterm_COL_HDL     object
 90   valor_COL_LDL         object
 91   fecdeterm_COL_LDL     object
 92   valor_COLEST          object
 93   fecdeterm_COLEST      object
 94   valor_CREAT           object
 95   fecdeterm_CREAT       object
 96   valor_GLU_SUERO       object
 97   fecdeterm_GLU_SUERO   object
 98   valor_INSULINA        object
 99   fecdeterm_INSULINA    object
 100  valor_PCR             object
 101  fecdeterm_PCR         object
 102  valor_TRIG            object
 103  fecdeterm_TRIG        object
 104  MATRIZ_SANGRE         int64
 105  valor_EAG             object
 106  fecdeterm_EAG         object
 107  valor_HB1AC           object
 108  fecdeterm_HB1AC       object
 109  MATRIZ_SUEROMICRO     object
 110  valor_FERRITINA       object
 111  fecdeterm_FERRITINA   object
 112  valor_FOL             object
 113  fecdeterm_FOL         object
 114  valor_HCST            object
 115  fecdeterm_HCST        object
 116  valor_PROTCREAC       object
 117  fecdeterm_PROTCREAC   object
 118  valor_STFR_FEB23      object
 119  fecdeterm_STFR_FEB23  object
 120  valor_VIT_B12         object
 121  fecdeterm_VIT_B12     object
 122  valor_VIT_D           object
 123  fecdeterm_VIT_D       object
 124  ponde_v               object
 125  cuenta_mic            int64
 126  ponde_m12a49          object
 127  ponde_m0a11           object
 128  estrato               int64
 129  region                int64
 130  est_sel               int64
 131  upm                   object
dtypes: int64(26), object(106)
memory usage: 14.0+ MB

In [350]:
# Separar variables categoricas y numericas
categorical_vars = data.select_dtypes(include=['object', 'category']).columns
numerical_vars = data.select_dtypes(include=['number']).columns
print("Categorical Variables:", categorical_vars)
print("Numerical Variables:", numerical_vars)

df_cat = data[categorical_vars]
df_num = data[numerical_vars]

Categorical Variables: Index(['FOLIO_I', 'FOLIO_INT', 'hora_ini_1', 'fecha_ini_1', 'hora_fin_1',
       'fecha_fin_1', 'hora_ini_2', 'fecha_ini_2', 'hora_fin_2', 'fecha_fin_2',
       ...
       'valor_STFR_FEB23', 'fecdeterm_STFR_FEB23', 'valor_VIT_B12',
       'fecdeterm_VIT_B12', 'valor_VIT_D', 'fecdeterm_VIT_D', 'ponde_v',
       'ponde_m12a49', 'ponde_m0a11', 'upm'],
      dtype='object', length=106)
Numerical Variables: Index(['t_hora', 't_min', 't_sumai', 't_sumaf', 'tiempo1', 'resultado_1',
       'tiempo2', 'resultado_2', 'tiempo3', 'resultado_3', 'tiempo4',
       'resultado_4', 'localizado', 'entidad', 'municipio', 'h0302', 'h0303',
       'nota1', 'tiempo', 'completa', 'MATRIZ_SUERO', 'MATRIZ_SANGRE',
       'cuenta_mic', 'estrato', 'region', 'est_sel'],
      dtype='object')

In [351]:

for col in df_cat.columns:
    print(f"Value counts for {col}:")
    print(df_cat[col].value_counts())
    print("\n")

for col in df_num.columns:
    print(f"Descriptive statistics for {col}:")
    print(df_num[col].describe())
    print("\n")

Value counts for FOLIO_I:
FOLIO_I
2022_31098022    7
2022_12001117    7
2022_20016023    6
2022_32039021    6
2022_16107011    6
                ..
2022_15031034    1
2022_15033001    1
2022_15033005    1
2022_15033008    1
2022_32056030    1
Name: count, Length: 7083, dtype: int64


Value counts for FOLIO_INT:
FOLIO_INT
2022_01001004_01    1
2022_19039062_02    1
2022_19039051_04    1
2022_19039051_07    1
2022_19039052_02    1
                   ..
2022_11020099_03    1
2022_11020101_01    1
2022_11020101_03    1
2022_11020102_02    1
2022_32056030_02    1
Name: count, Length: 13899, dtype: int64


Value counts for hora_ini_1:
hora_ini_1
08:58:56    4
13:52:53    4
16:28:20    4
14:16:46    4
15:08:02    4
           ..
20:09:31    1
09:52:18    1
09:57:36    1
09:07:23    1
17:04:55    1
Name: count, Length: 12536, dtype: int64


Value counts for fecha_ini_1:
fecha_ini_1
11/12/2022    423
14/11/2022    334
13/12/2022    328
22/10/2022    300
12/12/2022    299
             ...
28/08/2022      5
26/08/2022      4
04/09/2022      3
25/11/2021      1
31/08/2022      1
Name: count, Length: 110, dtype: int64


Value counts for hora_fin_1:
hora_fin_1
16:33:30    5
18:23:34    4
23:31:13    4
00:10:33    4
15:32:25    4
           ..
10:25:19    1
12:17:11    1
18:56:52    1
18:59:20    1
09:38:19    1
Name: count, Length: 12554, dtype: int64


Value counts for fecha_fin_1:
fecha_fin_1
11/12/2022    424
14/11/2022    335
13/12/2022    328
22/10/2022    299
12/12/2022    299
             ...
28/08/2022      5
26/08/2022      4
04/09/2022      3
25/11/2021      1
31/08/2022      1
Name: count, Length: 110, dtype: int64


Value counts for hora_ini_2:
hora_ini_2
            10530
00:52:17        2
22:07:23        2
15:25:49        2
20:15:12        2
            ...
18:59:27        1
13:33:07        1
20:06:30        1
20:20:03        1
22:58:27        1
Name: count, Length: 3289, dtype: int64


Value counts for fecha_ini_2:
fecha_ini_2
              10530
11/12/2022      216
22/10/2022      214
12/12/2022      157
24/10/2022      146
              ...
02/09/2022        1
29/08/2022        1
28/08/2022        1
27/08/2022        1
15/09/2022        1
Name: count, Length: 106, dtype: int64


Value counts for hora_fin_2:
hora_fin_2
            10530
12:16:32        3
16:05:22        2
14:40:21        2
14:52:32        2
            ...
16:19:50        1
18:54:01        1
09:08:29        1
16:31:22        1
22:58:35        1
Name: count, Length: 3284, dtype: int64


Value counts for fecha_fin_2:
fecha_fin_2
              10530
11/12/2022      217
22/10/2022      214
12/12/2022      157
24/10/2022      146
              ...
02/09/2022        1
29/08/2022        1
28/08/2022        1
27/08/2022        1
15/09/2022        1
Name: count, Length: 106, dtype: int64


Value counts for hora_ini_3:
hora_ini_3
            11202
13:30:19        2
17:05:06        2
13:21:57        2
22:26:15        2
            ...
10:31:26        1
00:15:13        1
07:27:45        1
15:09:05        1
22:58:42        1
Name: count, Length: 2653, dtype: int64


Value counts for fecha_ini_3:
fecha_ini_3
              11202
11/12/2022      215
22/10/2022      207
12/12/2022      150
24/10/2022      142
              ...
28/08/2022        1
07/09/2022        1
06/11/2022        1
17/11/2022        1
13/10/2022        1
Name: count, Length: 85, dtype: int64


Value counts for hora_fin_3:
hora_fin_3
            11202
23:40:04        3
23:27:30        2
23:43:53        2
16:20:03        2
            ...
15:15:43        1
15:22:52        1
16:03:36        1
16:04:24        1
22:58:47        1
Name: count, Length: 2631, dtype: int64


Value counts for fecha_fin_3:
fecha_fin_3
              11202
11/12/2022      215
22/10/2022      207
12/12/2022      150
24/10/2022      142
              ...
28/08/2022        1
06/11/2022        1
13/10/2022        1
17/11/2022        1
26/10/2022        1
Name: count, Length: 84, dtype: int64


Value counts for hora_ini_4:
hora_ini_4
            11287
00:29:42        3
21:37:36        2
00:55:23        2
12:17:13        2
            ...
00:56:47        1
00:15:51        1
11:59:56        1
19:34:04        1
22:58:55        1
Name: count, Length: 2555, dtype: int64


Value counts for fecha_ini_4:
fecha_ini_4
              11287
11/12/2022      222
24/10/2022      204
12/12/2022      146
22/10/2022      141
              ...
13/09/2022        1
25/11/2022        1
05/10/2022        1
06/11/2022        1
16/10/2022        1
Name: count, Length: 72, dtype: int64


Value counts for hora_fin_4:
hora_fin_4
            11287
20:15:33        2
22:13:25        2
14:22:28        2
00:02:50        2
            ...
00:47:36        1
00:46:18        1
00:54:58        1
00:55:59        1
22:59:10        1
Name: count, Length: 2555, dtype: int64


Value counts for fecha_fin_4:
fecha_fin_4
              11287
11/12/2022      221
24/10/2022      204
12/12/2022      147
22/10/2022      142
              ...
13/09/2022        1
25/11/2022        1
05/10/2022        1
06/11/2022        1
16/10/2022        1
Name: count, Length: 72, dtype: int64


Value counts for hora_ini:
hora_ini
08:58:56    4
13:52:53    4
16:28:20    4
14:16:46    4
15:08:02    4
           ..
20:09:31    1
09:52:18    1
09:57:36    1
09:07:23    1
17:04:55    1
Name: count, Length: 12536, dtype: int64


Value counts for fecha_ini:
fecha_ini
11/12/2022    423
14/11/2022    334
13/12/2022    328
22/10/2022    300
12/12/2022    299
             ...
28/08/2022      5
26/08/2022      4
04/09/2022      3
25/11/2021      1
31/08/2022      1
Name: count, Length: 110, dtype: int64


Value counts for desc_ent:
desc_ent
11 GUANAJUATO                         1495
19 NUEVO LEÓN                         1383
15 MÉXICO                              723
09 CIUDAD DE MÉXICO                    664
13 HIDALGO                             543
16 MICHOACÁN DE OCAMPO                 517
06 COLIMA                              486
08 CHIHUAHUA                           483
30 VERACRUZ DE IGNACIO DE LA LLAVE     481
07 CHIAPAS                             451
05 COAHUILA DE ZARAGOZA                403
26 SONORA                              377
20 OAXACA                              376
12 GUERRERO                            367
23 QUINTANA ROO                        358
28 TAMAULIPAS                          351
25 SINALOA                             346
27 TABASCO                             330
02 BAJA CALIFORNIA                     323
03 BAJA CALIFORNIA SUR                 320
04 CAMPECHE                            319
31 YUCATÁN                             313
29 TLAXCALA                            312
32 ZACATECAS                           301
17 MORELOS                             278
14 JALISCO                             263
01 AGUASCALIENTES                      251
24 SAN LUIS POTOSÍ                     243
10 DURANGO                             240
22 QUERÉTARO                           226
21 PUEBLA                              225
18 NAYARIT                             151
Name: count, dtype: int64


Value counts for desc_mun:
desc_mun
020 LEÓN                           414
007 IZTAPALAPA                     240
039 MONTERREY                      178
002 CAMPECHE                       175
003 LA PAZ                         173
                                  ...
035 SOLEDAD DE GRACIANO SÁNCHEZ      8
009 CIUDAD MADERO                    7
019 SAN PEDRO GARZA GARCÍA           3
035 NORIA DE ÁNGELES                 3
027 LOS HERRERAS                     3
Name: count, Length: 277, dtype: int64


Value counts for fech_nac:
fech_nac
            1886
99999999      45
24072012       5
18022011       5
14102019       5
            ...
13012003       1
11111975       1
02111977       1
18101977       1
21081991       1
Name: count, Length: 9577, dtype: int64


Value counts for sc:
sc
1    12013
      1886
Name: count, dtype: int64


Value counts for sv:
sv
0    8846
1    3167
     1886
Name: count, dtype: int64


Value counts for sh:
sh
0    11491
      1886
1      522
Name: count, dtype: int64


Value counts for sm:
sm
0    8322
1    3691
     1886
Name: count, dtype: int64


Value counts for int_hemoglobina:
int_hemoglobina
1    6082
0    5931
     1886
Name: count, dtype: int64


Value counts for nota11:
nota11
1    9822
     4077
Name: count, dtype: int64


Value counts for nota00:
nota00
1    9687
     4212
Name: count, dtype: int64


Value counts for sc01:
sc01
1    9291
     4453
2      67
5      39
6      32
4      12
3       5
Name: count, dtype: int64


Value counts for sc02:
sc02
         4548
01:00    2233
02:00    1087
03:00     954
04:00     728
         ...
11:21       1
09:10       1
09:08       1
09:40       1
03:15       1
Name: count, Length: 297, dtype: int64


Value counts for sc03:
sc03
5    8926
     4548
4     250
3     109
2      40
1      26
Name: count, dtype: int64


Value counts for sc04:
sc04
            4548
327F0010       2
327F0009       2
309F0135       1
308F0173       1
            ...
506F0031       1
506F0032       1
506F0033       1
506F0034       1
244F0152       1
Name: count, Length: 9350, dtype: int64


Value counts for nota01:
nota01
     11414
1     2485
Name: count, dtype: int64


Value counts for san01:
san01
     11417
1     2092
5      289
3       47
2       22
4       19
6       13
Name: count, dtype: int64


Value counts for san02:
san02
         11785
08:20       48
08:00       46
09:00       40
08:10       33
         ...
10:41        1
11:33        1
12:13        1
12:23        1
16:11        1
Name: count, Length: 499, dtype: int64


Value counts for san03:
san03
            11785
513C0007        1
516C0020        1
514C0012        1
514C0013        1
            ...
506C0002        1
506C0003        1
504C0003        1
504C0002        1
244C0043        1
Name: count, Length: 2115, dtype: int64


Value counts for san04:
san04
      11785
12      528
11      331
10      309
8       287
9       174
13      128
14       92
7        65
6        47
15       44
16       37
18       16
17       13
2        12
1        11
4         8
5         8
0         2
3         2
Name: count, dtype: int64


Value counts for san05:
san05
            11785
513S0007        1
516S0020        1
514S0012        1
514S0013        1
            ...
506S0002        1
506S0003        1
504S0005        1
504S0002        1
244S0043        1
Name: count, Length: 2115, dtype: int64


Value counts for san06:
san06
            11785
513T0007        1
516T0020        1
514T0012        1
514T0013        1
            ...
506T0002        1
506T0003        1
504T0005        1
504T0002        1
244T0043        1
Name: count, Length: 2115, dtype: int64


Value counts for nota02:
nota02
     9083
1    4816
Name: count, dtype: int64


Value counts for hb01:
hb01
     9084
1    3999
3     667
2     104
4      45
Name: count, dtype: int64


Value counts for hb02:
hb02
        9900
13,5     122
13,6     114
13,4     113
14       111
        ...
9,4        1
7,5        1
5,5        1
19,7       1
4          1
Name: count, Length: 128, dtype: int64


Value counts for hb03:
hb03
     10700
2     3123
1       76
Name: count, dtype: int64


Value counts for hb04:
hb04
            13763
325H0006        1
326H0015        1
308H0004        1
308H0005        1
            ...
516H0011        1
516H0013        1
516H0010        1
326H0002        1
350H0002        1
Name: count, Length: 137, dtype: int64


Value counts for hb05:
hb05
     10293
3     3445
1      159
2        2
Name: count, dtype: int64


Value counts for hb06a:
hb06a
     10293
1     2548
2     1058
Name: count, dtype: int64


Value counts for hb06b:
hb06b
      11351
22      178
18      160
24      156
26      148
23      143
27      128
21      127
14      124
19      124
25      111
17      110
16      109
29      102
20      101
13       91
28       91
12       75
11       71
15       69
31       60
10       48
9        40
30       36
8        32
33       30
32       28
7        17
6         9
36        8
5         4
34        3
35        3
3         3
37        3
39        2
4         2
38        1
2         1
Name: count, dtype: int64


Value counts for hb07a:
hb07a
     10293
1     2458
2     1148
Name: count, dtype: int64


Value counts for hb07b:
hb07b
      11441
95       65
84       50
90       49
71       47
      ...
2         2
12        2
11        2
7         1
8         1
Name: count, Length: 97, dtype: int64


Value counts for hb08:
hb08
           10293
2109923     3477
1             42
2409923       13
210923         9
210993         6
219923         4
2309923        4
2199023        3
1210992        2
201            2
210992         2
2109953        2
2190923        2
2109223        2
2019923        2
2109023        2
1209923        2
2109992        1
202209         1
2163099        1
2169923        1
2108992        1
24093          1
9210992        1
213923         1
63             1
2100923        1
45             1
21099          1
5426908        1
2109993        1
2009923        1
2109913        1
5              1
2              1
2190023        1
64             1
2106923        1
2109926        1
2109933        1
2010992        1
52             1
2129923        1
629181         1
86             1
2109922        1
2109523        1
Name: count, dtype: int64


Value counts for hb09:
hb09
            10293
20220906      395
20220907      205
20221016      167
20220909      143
            ...
20221028        1
20220806        1
20220901        1
20220930        1
20221024        1
Name: count, Length: 75, dtype: int64


Value counts for hb10:
hb10
         10293
MQ352      170
MQ351      153
MQ300      137
MQ341      135
MQ358      131
MQ308      130
MQ350      128
MQ301      126
MQ317      124
MQ335      123
MQ342      123
MQ310      121
MQ245      121
MQ334      120
MQ325      119
MQ361      115
MQ326      115
MQ302      114
MQ318      112
MQ340      110
MQ244      108
MQ250      106
MQ243      103
MQ319      103
MQ327      102
MQ252       92
MQ333       85
MQ360       80
MQ309       77
MQ253       65
MQ507       36
MQ516       31
MQ506       25
MQ514       24
MQ513       23
MQ515       17
MQ353        1
gsanc        1
Name: count, dtype: int64


Value counts for hb11:
hb11
    13899
Name: count, dtype: int64


Value counts for nota03:
nota03
     10960
1     2939
Name: count, dtype: int64


Value counts for mc01:
mc01
     10960
1     2264
5      454
3       98
4       60
2       50
6       13
Name: count, dtype: int64


Value counts for mc02:
mc02
         11585
19:00       20
08:20       18
14:00       18
13:20       17
         ...
15:14        1
11:24        1
04:39        1
07:57        1
20:55        1
Name: count, Length: 732, dtype: int64


Value counts for mc03:
mc03
            11585
326M0089        1
253M0027        1
333M0023        1
333M0024        1
            ...
302M0024        1
302M0025        1
302M0026        1
302M0027        1
244M0038        1
Name: count, Length: 2315, dtype: int64


Value counts for comentario:
comentario
                                                                            6256
NINGUNO                                                                     5437
NINGUNA                                                                      546
NO                                                                           366
SE NEGO                                                                      121
                                                                            ...
LE HACEN BUERLA SU FAMILIA Y SE NEGO A QUE LO MIDIERAMOS Y PESARAMOS           1
NO DEJABA DE MOVERSE, ÚNICAMENTE SE OBTUVO LO NECESARIO PARA HEMOGLOBINA       1
LA MAMA SE NEGO POR QUE  ERA MUY PEQUEÑA LA                                    1
LLEGAMOS A LA MUESTRA Y NUNCA SALIO                                            1
LA ENTREVISTADA SE DESMAYO                                                     1
Name: count, Length: 667, dtype: int64


Value counts for hora_fin:
hora_fin
15:35:31    4
15:32:25    4
12:28:15    4
16:33:30    4
14:31:17    3
           ..
15:03:22    1
15:31:50    1
15:30:42    1
15:32:36    1
09:38:19    1
Name: count, Length: 12591, dtype: int64


Value counts for fecha_fin:
fecha_fin
11/12/2022    436
24/10/2022    363
13/12/2022    334
14/11/2022    333
12/12/2022    308
             ...
28/08/2022      5
26/08/2022      4
04/09/2022      3
25/11/2021      1
31/08/2022      1
Name: count, Length: 110, dtype: int64


Value counts for otroent:
otroent
                                                                13727
CAMBIO DE DOMICILIO                                                95
CAMBIO  DE DOMICILIO                                                2
NO SE ENCUENTRA VIVIENDA                                            2
CONTAGIADO DE COVID                                                 2
                                                                ...
SE ENCONTRO LA VIVIENDA PERO NO LOS SELECCIONADOS                   1
PACIENTE ONCOLOGICO                                                 1
SUJETO DE ESTUDIO CAMBIO DE DOMICILIO ESTADOS UNIDOS                1
REALIZAN FUNERAL EN VIVIENDA                                        1
SELECCIONADO NO VIVE EN VIVIENDA DE ACUERDO A LA CARTOGRAFÍA        1
Name: count, Length: 72, dtype: int64


Value counts for valor_AC_URICO:
valor_AC_URICO
        11808
4,5        74
4,3        72
4,8        69
4          67
        ...
10,3        1
,4          1
9,6         1
62          1
9,7         1
Name: count, Length: 88, dtype: int64


Value counts for fecdeterm_AC_URICO:
fecdeterm_AC_URICO
              11808
12/13/2022      271
10/31/2022      263
12/19/2022      243
11/7/2022       224
12/20/2022      197
10/10/2022      176
11/28/2022      168
11/17/2022      136
10/3/2022       133
12/21/2022      114
11/25/2022       94
10/13/2022       58
10/10/2021       13
11/21/2022        1
Name: count, dtype: int64


Value counts for valor_ALBU:
valor_ALBU
       11808
4        159
4,1      130
4,2      127
3,9      125
3,8      117
4,3      109
4,4       97
3,6       96
3,3       95
3,4       80
3,7       80
3,5       78
3         76
3,2       74
4,5       65
3,1       60
2,9       56
2,8       52
4,6       44
2,7       42
2,5       40
2,3       35
4,7       35
2,6       31
4,8       24
2,4       24
2,2       22
2         19
1,9       18
1,5       13
1,7       12
2,1       11
1,6        8
5          8
4,9        8
1,8        7
5,1        5
1          2
5,2        2
1,2        1
6          1
1,4        1
5,3        1
,8         1
Name: count, dtype: int64


Value counts for fecdeterm_ALBU:
fecdeterm_ALBU
              11808
12/13/2022      271
10/31/2022      263
12/19/2022      242
11/7/2022       224
12/20/2022      197
10/10/2022      176
11/28/2022      168
11/17/2022      136
10/3/2022       133
12/21/2022      114
11/25/2022       94
10/13/2022       58
10/10/2021       13
12/31/2022        1
11/21/2022        1
Name: count, dtype: int64


Value counts for valor_COL_HDL:
valor_COL_HDL
       11808
34        91
38        88
40        84
42        81
       ...
141        1
79         1
89         1
133        1
9          1
Name: count, Length: 82, dtype: int64


Value counts for fecdeterm_COL_HDL:
fecdeterm_COL_HDL
              11808
12/13/2022      271
10/31/2022      263
12/19/2022      243
11/7/2022       224
12/20/2022      197
10/10/2022      176
11/28/2022      168
11/17/2022      136
10/3/2022       133
12/21/2022      114
11/25/2022       94
10/13/2022       58
10/10/2021       13
11/21/2022        1
Name: count, dtype: int64


Value counts for valor_COL_LDL:
valor_COL_LDL
         11808
83          39
86          39
92          36
94          34
         ...
188          1
177          1
160          1
178          1
108,9        1
Name: count, Length: 174, dtype: int64


Value counts for fecdeterm_COL_LDL:
fecdeterm_COL_LDL
              11808
12/13/2022      271
10/31/2022      263
12/19/2022      243

LIMPIEZA DE DATOS SIN CONOCIMIENTO MEDICO

In [352]:
# Importar diccionario de datos
dict_data = pd.read_excel('../data/ensanut2022_muestras-diccionario.xlsx')
dict_data

,Unnamed: 0,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4
0,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...
144,estrato,129,Estrato urbanidad/ruralidad,Nominal,9
145,region,130,Region o zona de trabajo,Nominal,8
146,est_sel,131,Estrato de seleccion,Escala,9
147,upm,132,Unidad primaria de muestreo,Nominal,26
148,Variables en el archivo de trabajo,NaN,NaN,NaN,NaN

In [353]:
# Eliminar las primeras 18 filas que no contienen información relevante
dict_data = dict_data.iloc[16:].reset_index(drop=True)
dict_data.columns = ['Variable', 'Posicion', 'Etiqueta', 'Nivel de Medicion', 'Ancho de columna']
dict_data

,Variable,Posicion,Etiqueta,Nivel de Medicion,Ancho de columna
0,FOLIO_I,1,Folio,Nominal,15
1,FOLIO_INT,2,Folio de integrante,Nominal,18
2,t_hora,3,TIEMPO HORA,Escala,8
3,t_min,4,TIEMPO MINUTOS,Escala,7
4,t_sumai,5,TIEMPO SUMA INICIO,Escala,9
...,...,...,...,...,...
128,estrato,129,Estrato urbanidad/ruralidad,Nominal,9
129,region,130,Region o zona de trabajo,Nominal,8
130,est_sel,131,Estrato de seleccion,Escala,9
131,upm,132,Unidad primaria de muestreo,Nominal,26
132,Variables en el archivo de trabajo,NaN,NaN,NaN,NaN

In [354]:
# Mostrar etiquetas de las variables categoricas
for var in categorical_vars:
    etiquetas = dict_data[dict_data['Variable'] == var]['Etiqueta'].values
    if len(etiquetas) > 0:
        print(f"{var}: {etiquetas[0]}")
    else:
        print(f"No se encontraron etiquetas para {var}")

FOLIO_I: Folio
FOLIO_INT: Folio de integrante
hora_ini_1: Hora de Inicio 1
fecha_ini_1: Fecha de Inicio 1
hora_fin_1: Hora termino 1
fecha_fin_1: Fecha termino 1
hora_ini_2: Hora de Inicio 2
fecha_ini_2: Fecha de Inicio 2
hora_fin_2: Hora de Termino 2
fecha_fin_2: Fecha de Termino 2
hora_ini_3: Hora de Inicio 3
fecha_ini_3: Fecha de Inicio 3
hora_fin_3: Hora de Termino 3
fecha_fin_3: Fecha de Termino 3
hora_ini_4: Hora de Inicio 4
fecha_ini_4: Fecha de Inicio 4
hora_fin_4: Hora de Termino 4
fecha_fin_4: Fecha de Termino 4
hora_ini: Hora de Inicio
fecha_ini: Fecha de inicio
desc_ent: DESC_ENT
desc_mun: DESC_MUN
fech_nac: Fecha de Nacimiento
sc: SELECCIONADO PARA SANGRE CAPILAR
sv: SELECCIONADO PARA SANGRE VENOSA  COVID19
sh: SELECCIONADO PARA SANGRE VENOSA  ANEMIA
sm: SELECCIONADO PARA SANGRE VENOSA  MICRONUTRIMENTOS
int_hemoglobina: SELECCIONADO PARA SANGRE TOTAL DE MICRO NUTRIMENTOS
nota11: Información de la toma de muestras de sangre
nota00: NOTA00
sc01: SC01. REGISTRAR EL RESULTADO DE LA MUESTRA CAPILAR
sc02: SC02. ¿CUÁNTAS HORAS PASARON DESDE QUE (NOMBRE) TOMÓ EL ÚLTIMO ALIMENTO
sc03: SC03. ANOTAR EL NÚMERO DE SPOTS COMPLETAMENTE LLENOS (DE 1 A 5)
sc04: SC04. ANOTAR ETIQUETA PARA PAPEL FILTRO QUE CONTIENE LA MUESTRA PARA COVID-19
nota01: TOMA DE MUESTRA
san01: SAN01. REGISTRAR EL RESULTADO DE LA TOMA DE MUESTRA DE SANGRE VENOSA
san02: SAN02. ANOTAR LA HORA EN QUE FUE TOMADA LA MUESTRA UTILIZANDO EL FORMATO DE 24 H
san03: SAN03. FETIQUETA DEL TUBO AMARILLO QUE CONTIENE LA MUESTRA PARA COVID-19
san04: SAN04. ¿CUÁNTAS HORAS PASARON DESDE QUE (NOMBRE) TOMÓ EL ÚLTIMO ALIMENTO?
san05: SAN05. ETIQUETA DEL TUBO AMARILLO QUE CONTIENE LA MUESTRA PARA ENFERMEDADES CRÓN
san06: SAN06. ETIQUETA DEL TUBO MORADO QUE CONTIENE LA MUESTRA PARA ENFERMEDADES CRÓNIC
nota02: MUESTRA DE SANGRE VENOSA PARA ANEMIA
hb01: HB01. REGISTRAR EL RESULTADO DE LA MEDICIÓN DE HEMOGLOBINA
hb02: HB02. ANOTE LA CONCENTRACIÓN DE HEMOGLOBINA (HEMOCUE)
hb03: HB03. ¿ES SELECCIONADO PARA VALIDACION?
hb04: HB04. ANOTAR ETIQUETA DEL TUBO MORADO QUE CONTIENE MUESTRA PARA HEMOGLOBINA
hb05: HB05. HUBO NECESIDAD DE CONSERVAR EL HEMOCUE EN UNA TEMPERATURA DIFERENTE DEL AM
hb06a: HB06A. ¿FUE POSIBLE REGISTRAR LA TEMPERATURA?
hb06b: HB06B. REGISTRAR LA TEMPERATURA AMBIENTE
hb07a: HB07A. ¿FUE POSIBLE REGISTRAR LA HUMEDAD RELATIVA?
hb07b: HB07B. REGISTRAR LA HUMEDAD AMBIENTAL
hb08: HB08. REGISTRE EL NÚMERO DE LOTE DE CUBETAS QUE UTILIZO
hb09: HB09. REGISTRAR FECHA EN QUE SE ABRIÓ EL BOTE DE CUBETAS
hb10: HB10.ANOTE EL NÚMERO ECONÓMICO DE HEMOCUE ASIGNADO
hb11: HB11. CLAVE DEL MUESTRISTA
nota03: MUESTRA MICRONUTRIMENTOS
mc01: MC01. REGISTRAR EL RESULTADO DE LA TOMA DE MUESTRA VENOSA
mc02: MC02. ANOTE LA HORA EN QUE FUE TOMADA LA MUESTRA UTILIZANDO EL RELOJ DE 24 HORAS
mc03: MC03. ANOTAR ETIQUETA DEL TUBO AMARILLO QUE CONTIENE LA MUESTRA PARA MICRONUTRIM
comentario: ¿Algún comentario de la entrevista?
hora_fin: Hora de termino
fecha_fin: Fecha de Termino
otroent: Especifique otro resultado de entrevista
valor_AC_URICO: Resultado  Ácido úrico mg/dl
fecdeterm_AC_URICO: Fecha determinación  Ácido úrico
valor_ALBU: Resultado  Albúmina g/dL
fecdeterm_ALBU: Fecha determinación  Albúmina
valor_COL_HDL: Resultado  Colesterol HDL mg/dl
fecdeterm_COL_HDL: Fecha determinación  Colesterol HDL
valor_COL_LDL: Resultado  Colesterol LDL mg/dl
fecdeterm_COL_LDL: Fecha determinación  Colesterol LDL
valor_COLEST: Resultado  Colesterol total mg/dl
fecdeterm_COLEST: Fecha determinación  Colesterol total
valor_CREAT: Resultado  Creatinina mg/dl
fecdeterm_CREAT: Fecha determinación  Creatinina
valor_GLU_SUERO: Resultado  Glucosa mg/dl
fecdeterm_GLU_SUERO: Fecha determinación  Glucosa
valor_INSULINA: Resultado  Insulina micro UI/ml
fecdeterm_INSULINA: Fecha determinación  Insulina
valor_PCR: Resultado  Proteína C Reactiva mg/dL
fecdeterm_PCR: Fecha determinación Proteína C Reactiva mg/dL
valor_TRIG: Resultado  Triglicéridos mg/dl
fecdeterm_TRIG: Fecha determinación  Triglicéridos
valor_EAG: Resultado Glucosa Promedio Estimada mg/dL
fecdeterm_EAG: Fecha determinación Glucosa Promedio Estimada mg/dL
valor_HB1AC: Resultado  Hemoglobina glucosilada. %
fecdeterm_HB1AC: Fecha determinación  Hemoglobina glucosilada.
MATRIZ_SUEROMICRO: Registro con muestra de suero micronutrimentos analizada por el INNSZ
valor_FERRITINA: Resultado Ferritina ng/mL
fecdeterm_FERRITINA: Fecha determinación Ferritina ng/mL
valor_FOL: Resultado Folato ng/mL
fecdeterm_FOL: Fecha determinación Folato ng/mL
valor_HCST: Resultado Homocisteina micromol/L
fecdeterm_HCST: Fecha determinación Homocisteina
valor_PROTCREAC: Resultado  Proteína C Reactiva mg/L
fecdeterm_PROTCREAC: Fecha determinación  Proteína C Reactiva
valor_STFR_FEB23: Resultado Receptor de Transferrina mg/L
fecdeterm_STFR_FEB23: Fecha determinación Receptor de Transferrina
valor_VIT_B12: Resultado Vitamina B12 pg/mL
fecdeterm_VIT_B12: Fecha determinación  Vitamina B12 pg/mL
valor_VIT_D: Resultado Vitamina D ng/mL
fecdeterm_VIT_D: Fecha determinación Vitamina D ng/mL
ponde_v: ponderador venosa 20+
ponde_m12a49: ponderador micro-nutrientes
ponde_m0a11: ponderador micro-nutrientes
upm: Unidad primaria de muestreo

In [355]:
# Lista de variables cuyo nombre contiene "valor"
Cat_vars = dict_data.loc[dict_data['Variable'].str.contains("valor", case=False, na=False), 'Variable'].tolist()

# Añadir variables adicionales y eliminar duplicados
Cat_vars = list(['FOLIO_INT'] + Cat_vars + ['desc_ent', 'desc_mun'])

In [356]:
Cat_vars

['FOLIO_INT',
 'valor_AC_URICO',
 'valor_ALBU',
 'valor_COL_HDL',
 'valor_COL_LDL',
 'valor_COLEST',
 'valor_CREAT',
 'valor_GLU_SUERO',
 'valor_INSULINA',
 'valor_PCR',
 'valor_TRIG',
 'valor_EAG',
 'valor_HB1AC',
 'valor_FERRITINA',
 'valor_FOL',
 'valor_HCST',
 'valor_PROTCREAC',
 'valor_STFR_FEB23',
 'valor_VIT_B12',
 'valor_VIT_D',
 'desc_ent',
 'desc_mun']

VARIABLES SELECCIONADAS
Folio_INT: Para mapear los datos con otras bases de datos
"valor_...": Resultados clinicos/parametros medicos
['ponde_v', 'ponde_m12a49', 'ponde_m0a11', 'upm', 'MATRIZ_SUEROMICRO']: Diseño muestral

In [357]:
# Lo mismo con las numericas
# Mostrar etiquetas de las variables numericas
for var in numerical_vars:
    etiquetas = dict_data[dict_data['Variable'] == var]['Etiqueta'].values
    if len(etiquetas) > 0:
        print(f"{var}: {etiquetas[0]}")
    else:
        print(f"No se encontraron etiquetas para {var}")

t_hora: TIEMPO HORA
t_min: TIEMPO MINUTOS
t_sumai: TIEMPO SUMA INICIO
t_sumaf: TIEMPO SUMA FIN
tiempo1: Duración de la Entrevista 1
resultado_1: Resultado de entrevista 1
tiempo2: Duración de la Entrevista 2
resultado_2: Resultado de entrevista 2
tiempo3: Duración de la Entrevista 3
resultado_3: Resultado de entrevista 3
tiempo4: Duración de la Entrevista 4
resultado_4: Resultado de entrevista 4
localizado: localizado
entidad: Entidad
municipio: Municipio
h0302: Sexo
h0303: Edad
nota1: Consentimiento para realizar la entrevista
tiempo: Duración de la Entrevista
completa: Resultado de Entrevista
MATRIZ_SUERO: Registro con muestra de suero analizada por el INNSZ
MATRIZ_SANGRE: Registro con muestra de sangre total analizada por el INNSZ
cuenta_mic: Mediciones de micro-nutrientes
estrato: Estrato urbanidad/ruralidad
region: Region o zona de trabajo
est_sel:  Estrato de seleccion

In [358]:
#Añadir variables relevantes a la lista de numericas Sexo, Edad, Matriz_Suero, MAtriz_sangre 
Num_vars = ['h0302', 'h0303', 'estrato', 'region', 'est_sel']

In [359]:
Num_vars

['h0302', 'h0303', 'estrato', 'region', 'est_sel']

In [360]:
# data solo con las variables seleccionadas
data_selected = data[Cat_vars + Num_vars]
#data_selected.info()
data_selected.head(20)

,FOLIO_INT,valor_AC_URICO,valor_ALBU,valor_COL_HDL,valor_COL_LDL,valor_COLEST,valor_CREAT,valor_GLU_SUERO,valor_INSULINA,valor_PCR,...,valor_STFR_FEB23,valor_VIT_B12,valor_VIT_D,desc_ent,desc_mun,h0302,h0303,estrato,region,est_sel
0,2022_01001004_01,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,41,3,4,13
1,2022_01001008_01,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,58,3,4,13
2,2022_01001008_03,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,29,3,4,13
3,2022_01001009_02,"4,4","3,8",73,130,252,",62",111,"9,4",",29",...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,65,3,4,13
4,2022_01001011_01,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,67,3,4,13
5,2022_01001011_03,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,18,3,4,13
6,2022_01001012_02,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,68,3,4,13
7,2022_01001012_03,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,42,3,4,13
8,2022_01001013_01,"6,5","4,1",49,107,203,",91",106,"7,4",",07",...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,35,3,4,13
9,2022_01001013_02,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,52,3,4,13
10,2022_01001013_05,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,16,3,4,13
11,2022_01001013_06,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,9,3,4,13
12,2022_01001013_07,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,2,3,4,13
13,2022_01001015_01,"4,2","4,2",41,76,145,",71",109,"16,9",",12",...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,65,3,4,13
14,2022_01001017_02,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,2,70,3,4,13
15,2022_01001017_04,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,24,3,4,13
16,2022_01001017_05,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,18,3,4,13
17,2022_01001024_01,"4,6","3,8",42,84,139,",65",98,"18,1","2,23",...,"1,1",370,"16,5",01 AGUASCALIENTES,001 AGUASCALIENTES,2,30,3,4,13
18,2022_01001026_01,,,,,,,,,,...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,28,3,4,13
19,2022_01001027_01,"6,6","4,1",41,119,215,",83",253,"16,6",",21",...,,,,01 AGUASCALIENTES,001 AGUASCALIENTES,1,76,3,4,13

In [361]:
# Nuevo diccionario con las variabes seleccionadas
dict_selected = dict_data[dict_data['Variable'].isin(Cat_vars + Num_vars)]

# Liminar nivel de medicion y ancho de columna
dict_selected = dict_selected.drop(columns=['Nivel de Medicion', 'Ancho de columna'])

dict_selected

             Variable Posicion                                   Etiqueta
1           FOLIO_INT        2                        Folio de integrante
34           desc_ent       35                                   DESC_ENT
36           desc_mun       37                                   DESC_MUN
37              h0302       38                                       Sexo
38              h0303       39                                       Edad
84     valor_AC_URICO       85               Resultado  Ácido úrico mg/dl
86         valor_ALBU       87                   Resultado  Albúmina g/dL
88      valor_COL_HDL       89            Resultado  Colesterol HDL mg/dl
90      valor_COL_LDL       91            Resultado  Colesterol LDL mg/dl
92       valor_COLEST       93          Resultado  Colesterol total mg/dl
94        valor_CREAT       95                Resultado  Creatinina mg/dl
96    valor_GLU_SUERO       97                   Resultado  Glucosa mg/dl
98     valor_INSULINA       99            Resultado  Insulina micro UI/ml
100         valor_PCR      101       Resultado  Proteína C Reactiva mg/dL
102        valor_TRIG      103             Resultado  Triglicéridos mg/dl
105         valor_EAG      106  Resultado Glucosa Promedio Estimada mg/dL
107       valor_HB1AC      108      Resultado  Hemoglobina glucosilada. %
110   valor_FERRITINA      111                  Resultado Ferritina ng/mL
112         valor_FOL      113                     Resultado Folato ng/mL
114        valor_HCST      115          Resultado Homocisteina micromol/L
116   valor_PROTCREAC      117        Resultado  Proteína C Reactiva mg/L
118  valor_STFR_FEB23      119    Resultado Receptor de Transferrina mg/L
120     valor_VIT_B12      121               Resultado Vitamina B12 pg/mL
122       valor_VIT_D      123                 Resultado Vitamina D ng/mL
128           estrato      129                Estrato urbanidad/ruralidad
129            region      130                   Region o zona de trabajo
130           est_sel      131                       Estrato de seleccion

# En el Documento Socdem no encontre ninguna variable relevante, se podria. incluir
h1205: H1205 Desde febrero 2020 ¿Cuántas veces le han diagnosticado a (NOMBRE) COVID-19 por algún personal de salud?

Escolaridad: H0317A, H0317G, H0318

H0310 ¿(NOMBRE) tiene derecho o acceso a servicios médicos

- Reemplazar "," con .
- Cambiar el indicador de estado y municipios para que coincidan con los contaminantes y realizar el join a ambas db
- Construir DAG Medicas (3). Comparar con HC

# Join de municipios

In [362]:
data_selected['desc_ent'].value_counts()

desc_ent
11 GUANAJUATO                         1495
19 NUEVO LEÓN                         1383
15 MÉXICO                              723
09 CIUDAD DE MÉXICO                    664
13 HIDALGO                             543
16 MICHOACÁN DE OCAMPO                 517
06 COLIMA                              486
08 CHIHUAHUA                           483
30 VERACRUZ DE IGNACIO DE LA LLAVE     481
07 CHIAPAS                             451
05 COAHUILA DE ZARAGOZA                403
26 SONORA                              377
20 OAXACA                              376
12 GUERRERO                            367
23 QUINTANA ROO                        358
28 TAMAULIPAS                          351
25 SINALOA                             346
27 TABASCO                             330
02 BAJA CALIFORNIA                     323
03 BAJA CALIFORNIA SUR                 320
04 CAMPECHE                            319
31 YUCATÁN                             313
29 TLAXCALA                            312
32 ZACATECAS                           301
17 MORELOS                             278
14 JALISCO                             263
01 AGUASCALIENTES                      251
24 SAN LUIS POTOSÍ                     243
10 DURANGO                             240
22 QUERÉTARO                           226
21 PUEBLA                              225
18 NAYARIT                             151
Name: count, dtype: int64

In [363]:
data_selected['desc_mun'].value_counts()

desc_mun
020 LEÓN                           414
007 IZTAPALAPA                     240
039 MONTERREY                      178
002 CAMPECHE                       175
003 LA PAZ                         173
                                  ...
035 SOLEDAD DE GRACIANO SÁNCHEZ      8
009 CIUDAD MADERO                    7
019 SAN PEDRO GARZA GARCÍA           3
035 NORIA DE ÁNGELES                 3
027 LOS HERRERAS                     3
Name: count, Length: 277, dtype: int64

In [364]:
import unidecode

Se quiere:

1. Quitar los numeros del principio
2. Convertir todo a minusculas
3. Quitar los acentos (con unidecode)

In [365]:
data_selected['desc_ent'] = (
    data_selected['desc_ent']
    .str[3:]          
    .str.lower()             
    .apply(lambda x: unidecode.unidecode(x))
)

/var/folders/ys/2psfql1156jf72wjlnnt4vvc0000gn/T/ipykernel_62652/2396340755.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_selected['desc_ent'] = (

In [366]:
data_selected['desc_mun'] = (
    data_selected['desc_mun']
    .str[4:]          
    .str.lower()             
    .apply(lambda x: unidecode.unidecode(x))
)

/var/folders/ys/2psfql1156jf72wjlnnt4vvc0000gn/T/ipykernel_62652/3021006701.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_selected['desc_mun'] = (

In [367]:
data_selected = data_selected.rename(columns={
    "desc_ent": "Entidad",
    "desc_mun": "Municipio"
})
data_selected[['Entidad', 'Municipio']].head()

          Entidad       Municipio
0  aguascalientes  aguascalientes
1  aguascalientes  aguascalientes
2  aguascalientes  aguascalientes
3  aguascalientes  aguascalientes
4  aguascalientes  aguascalientes

In [368]:
# Move the two ID columns all the way to the right

cols = list(data_selected.columns)
# Take everything except the two you want to move
cols = [c for c in cols if c not in ['Entidad', 'Municipio']] 
# Put them at the end
cols = cols + ['Entidad', 'Municipio']
# Reorder dataframe
data_selected = data_selected[cols]

data_selected.head()

,FOLIO_INT,valor_AC_URICO,valor_ALBU,valor_COL_HDL,valor_COL_LDL,valor_COLEST,valor_CREAT,valor_GLU_SUERO,valor_INSULINA,valor_PCR,...,valor_STFR_FEB23,valor_VIT_B12,valor_VIT_D,h0302,h0303,estrato,region,est_sel,Entidad,Municipio
0,2022_01001004_01,,,,,,,,,,...,,,,2,41,3,4,13,aguascalientes,aguascalientes
1,2022_01001008_01,,,,,,,,,,...,,,,1,58,3,4,13,aguascalientes,aguascalientes
2,2022_01001008_03,,,,,,,,,,...,,,,2,29,3,4,13,aguascalientes,aguascalientes
3,2022_01001009_02,"4,4","3,8",73,130,252,",62",111,"9,4",",29",...,,,,2,65,3,4,13,aguascalientes,aguascalientes
4,2022_01001011_01,,,,,,,,,,...,,,,1,67,3,4,13,aguascalientes,aguascalientes

In [369]:
ent_mun = pd.read_csv('../data_util/Emisiones_municipio.csv')
ent_mun.head()

,Entidad,Municipio,SO_2,CO,NOx,COV,PM_010,PM_2_5,NH_3
0,Aguascalientes,Aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
1,Aguascalientes,Asientos,10.119,1568.412,831.565,2294.086,806.080,452.848,5182.038
2,Aguascalientes,Calvillo,15.910,2395.499,716.460,3500.021,281.688,110.000,380.880
3,Aguascalientes,Cosío,4.351,641.055,550.936,1529.717,93.845,42.697,2243.721
4,Aguascalientes,El Llano,7.539,1021.761,750.669,2188.581,237.434,92.468,5145.328

In [370]:
ent_mun['Entidad'] = (
    ent_mun['Entidad']        
    .str.lower()             
    .apply(lambda x: unidecode.unidecode(x))
)
ent_mun['Municipio'] = (
    ent_mun['Municipio']        
    .str.lower()             
    .apply(lambda x: unidecode.unidecode(x))
)

ent_mun[['Entidad', 'Municipio']].head()

          Entidad       Municipio
0  aguascalientes  aguascalientes
1  aguascalientes        asientos
2  aguascalientes        calvillo
3  aguascalientes           cosio
4  aguascalientes        el llano

In [371]:
data_merged = pd.merge(data_selected, ent_mun, on=['Entidad', 'Municipio'], how="left")
data_merged

,FOLIO_INT,valor_AC_URICO,valor_ALBU,valor_COL_HDL,valor_COL_LDL,valor_COLEST,valor_CREAT,valor_GLU_SUERO,valor_INSULINA,valor_PCR,...,est_sel,Entidad,Municipio,SO_2,CO,NOx,COV,PM_010,PM_2_5,NH_3
0,2022_01001004_01,,,,,,,,,,...,13,aguascalientes,aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
1,2022_01001008_01,,,,,,,,,,...,13,aguascalientes,aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
2,2022_01001008_03,,,,,,,,,,...,13,aguascalientes,aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
3,2022_01001009_02,"4,4","3,8",73,130,252,",62",111,"9,4",",29",...,13,aguascalientes,aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
4,2022_01001011_01,,,,,,,,,,...,13,aguascalientes,aguascalientes,907.175,51566.526,12511.863,21567.916,2601.617,1389.116,13748.263
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13894,2022_32056028_02,,,,,,,,,,...,323,zacatecas,zacatecas,168.293,17951.779,6752.996,4669.181,762.684,648.348,297.385
13895,2022_32056028_03,,,,,,,,,,...,323,zacatecas,zacatecas,168.293,17951.779,6752.996,4669.181,762.684,648.348,297.385
13896,2022_32056029_01,"5,5",4,44,96,171,",8",89,"6,1",",25",...,323,zacatecas,zacatecas,168.293,17951.779,6752.996,4669.181,762.684,648.348,297.385
13897,2022_32056029_03,"2,5","2,4",31,46,90,",4",58,"3,3",",02",...,323,zacatecas,zacatecas,168.293,17951.779,6752.996,4669.181,762.684,648.348,297.385
13898,2022_32056030_02,,,,,,,,,,...,323,zacatecas,zacatecas,168.293,17951.779,6752.996,4669.181,762.684,648.348,297.385

In [372]:
data_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13899 entries, 0 to 13898
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FOLIO_INT         13899 non-null  object
 1   valor_AC_URICO    13899 non-null  object
 2   valor_ALBU        13899 non-null  object
 3   valor_COL_HDL     13899 non-null  object
 4   valor_COL_LDL     13899 non-null  object
 5   valor_COLEST      13899 non-null  object
 6   valor_CREAT       13899 non-null  object
 7   valor_GLU_SUERO   13899 non-null  object
 8   valor_INSULINA    13899 non-null  object
 9   valor_PCR         13899 non-null  object
 10  valor_TRIG        13899 non-null  object
 11  valor_EAG         13899 non-null  object
 12  valor_HB1AC       13899 non-null  object
 13  valor_FERRITINA   13899 non-null  object
 14  valor_FOL         13899 non-null  object
 15  valor_HCST        13899 non-null  object
 16  valor_PROTCREAC   13899 non-null  object
 17  valor_STFR_FEB23  13899 non-null  object
 18  valor_VIT_B12     13899 non-null  object
 19  valor_VIT_D       13899 non-null  object
 20  h0302             13899 non-null  int64
 21  h0303             13899 non-null  int64
 22  estrato           13899 non-null  int64
 23  region            13899 non-null  int64
 24  est_sel           13899 non-null  int64
 25  Entidad           13899 non-null  object
 26  Municipio         13899 non-null  object
 27  SO_2              11525 non-null  float64
 28  CO                11525 non-null  float64
 29  NOx               11525 non-null  float64
 30  COV               11525 non-null  float64
 31  PM_010            11525 non-null  float64
 32  PM_2_5            11525 non-null  float64
 33  NH_3              11525 non-null  float64
dtypes: float64(7), int64(5), object(22)
memory usage: 3.6+ MB

In [374]:
cols = data_merged.columns[1:20]

data_merged[cols] = (
    data_merged[cols]
    .replace(r'^\s*$', np.nan, regex=True)
    .replace(",", ".", regex=True)          
    .astype(float)                          
)

In [375]:
data_merged.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13899 entries, 0 to 13898
Data columns (total 34 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   FOLIO_INT         13899 non-null  object
 1   valor_AC_URICO    2091 non-null   float64
 2   valor_ALBU        2091 non-null   float64
 3   valor_COL_HDL     2091 non-null   float64
 4   valor_COL_LDL     2091 non-null   float64
 5   valor_COLEST      2091 non-null   float64
 6   valor_CREAT       2091 non-null   float64
 7   valor_GLU_SUERO   2091 non-null   float64
 8   valor_INSULINA    2091 non-null   float64
 9   valor_PCR         2091 non-null   float64
 10  valor_TRIG        2091 non-null   float64
 11  valor_EAG         2063 non-null   float64
 12  valor_HB1AC       2063 non-null   float64
 13  valor_FERRITINA   2263 non-null   float64
 14  valor_FOL         2261 non-null   float64
 15  valor_HCST        2277 non-null   float64
 16  valor_PROTCREAC   2267 non-null   float64
 17  valor_STFR_FEB23  2073 non-null   float64
 18  valor_VIT_B12     2261 non-null   float64
 19  valor_VIT_D       2277 non-null   float64
 20  h0302             13899 non-null  int64
 21  h0303             13899 non-null  int64
 22  estrato           13899 non-null  int64
 23  region            13899 non-null  int64
 24  est_sel           13899 non-null  int64
 25  Entidad           13899 non-null  object
 26  Municipio         13899 non-null  object
 27  SO_2              11525 non-null  float64
 28  CO                11525 non-null  float64
 29  NOx               11525 non-null  float64
 30  COV               11525 non-null  float64
 31  PM_010            11525 non-null  float64
 32  PM_2_5            11525 non-null  float64
 33  NH_3              11525 non-null  float64
dtypes: float64(26), int64(5), object(3)
memory usage: 3.6+ MB

In [377]:
#data_selected.to_csv('../data_util/ensanut2022_muestras_selected.csv', index=False)
data_merged.to_csv('../data_util/ensanut2022_muestras_selected.csv', index=False)
dict_selected.to_csv('../data_util/ensanut2022_muestras_dicccionario_selected.csv', index=False)